## Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[2] # returns the value in a index 

2

In [7]:
arr[1:5] # sub array between indexes

array([1, 2, 3, 4])

In [8]:
arr[0:5] # = arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:] # index to end of the array

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)
slice_of_arr=arr[:6]


In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]=15

In [22]:
arr # cambia el original también

array([15, 15, 15, 15, 15, 15,  6,  7,  8,  9, 10])

In [23]:
arr_copy=arr.copy()
arr_copy[:]=20
print(arr_copy)
print(arr)

[20 20 20 20 20 20 20 20 20 20 20]
[15 15 15 15 15 15  6  7  8  9 10]


In [24]:
arr_2d=np.array([[21,21,3],[54,234,63],[1,65,43]])
arr_2d

array([[ 21,  21,   3],
       [ 54, 234,  63],
       [  1,  65,  43]])

In [26]:
#double bracket notation
arr_2d[0][2]   #row-column

3

In [28]:
#single bracket comma notation
arr_2d[0,2] #row-colum =arr_2d[0][2] 

3

In [37]:
#Sectiones of a matriz
arr_2d[:2,1:] #todo lo de la parte superior derecha sub matriz de 2x2
# :2 in the first dimension: This selects the first two rows of arr_2d (i.e., rows at indices 0 and 1).
# 1: in the second dimension: This selects all columns from the second column onward (i.e., starting from column index 1)

array([[ 21,   3],
       [234,  63]])

In [35]:
arr_2d[:2] 

array([[ 21,  21,   3],
       [ 54, 234,  63]])

In [38]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
bool_arr=arr >5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr] # returns the values that are true with the conditions

array([ 6,  7,  8,  9, 10])

In [44]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [45]:
arr[arr<3]

array([1, 2])

In [48]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
# get matrix [[13,14],[23,24]]
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])